# docker-compose.yml
version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - shared_ohc_network

networks:
  shared_ohc_network:
    external: true
